"""
You are given two strings s and t.
String t is generated by random shuffling string s 
and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
Example 2:
    Input: s = "", t = "y"
    Output: "y"
"""
def find_difference1(s, t):
    result = 0
    for i in s:
        result ^= ord(i)
    for i in t:
        result ^= ord(i)
    return chr(result)

def find_difference2(s, t):
    seen = list(s)
    for i in t:
        if i not in seen:
            return i
        else:
            seen.remove(i)
    return None

s1 = "abcd"
t1 = "abcde"
s2 = ""
t2 = "y"

print(find_difference1(s1, t1))
print(find_difference2(s2, t2))